"""initial_schema"""

from alembic import op
import sqlalchemy as sa

revision = "9b050acd3a68"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("endpoint", sa.String(length=2048), nullable=True),
        sa.Column("model", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("agent_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_agents_name_version"),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=False)
    op.create_table(
        "chaos_campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diagnosis_benchmarks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluation_suites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version", sa.String(length=128), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_name"), "experiments", ["name"], unique=False)
    op.create_table(
        "monitor_alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=400), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_alerts_scope"), "monitor_alerts", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_monitor_alerts_tenant"), "monitor_alerts", ["tenant"], unique=False
    )
    op.create_table(
        "monitor_tenants",
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("sampled_out", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("dropped_spans", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant"),
    )
    op.create_table(
        "monitor_traces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant", sa.String(length=128), nullable=False),
        sa.Column("external_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "external_id"),
    )
    op.create_index(
        op.f("ix_monitor_traces_created_at"),
        "monitor_traces",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_traces_status"), "monitor_traces", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_monitor_traces_tenant"), "monitor_traces", ["tenant"], unique=False
    )
    op.create_table(
        "regression_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("expected_tools", sa.JSON(), nullable=False),
        sa.Column("forbidden_tools", sa.JSON(), nullable=False),
        sa.Column("expected_documents", sa.JSON(), nullable=False),
        sa.Column("expected_behavior", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("tc_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_cases_name"), "test_cases", ["name"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("test_case_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["test_case_id"], ["test_cases.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_agent_id"), "runs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_index(
        op.f("ix_runs_test_case_id"), "runs", ["test_case_id"], unique=False
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("evaluator", sa.String(length=256), nullable=False),
        sa.Column("dimension", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluations_run_id"), "evaluations", ["run_id"], unique=False
    )
    op.create_table(
        "failures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("suspected_component", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_failures_run_id"), "failures", ["run_id"], unique=False)
    op.create_table(
        "run_diagnoses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "version", name="uq_diagnosis_run_version"),
    )
    op.create_table(
        "trace_spans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("parent_span_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("span_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("input", sa.JSON(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("span_metadata", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_span_id"], ["trace_spans.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trace_spans_run_id"), "trace_spans", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_trace_spans_trace_id"), "trace_spans", ["trace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trace_spans_trace_id"), table_name="trace_spans")
    op.drop_index(op.f("ix_trace_spans_run_id"), table_name="trace_spans")
    op.drop_table("trace_spans")
    op.drop_table("run_diagnoses")
    op.drop_index(op.f("ix_failures_run_id"), table_name="failures")
    op.drop_table("failures")
    op.drop_index(op.f("ix_evaluations_run_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_runs_test_case_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_agent_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_test_cases_name"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_table("regression_reports")
    op.drop_index(op.f("ix_monitor_traces_tenant"), table_name="monitor_traces")
    op.drop_index(op.f("ix_monitor_traces_status"), table_name="monitor_traces")
    op.drop_index(op.f("ix_monitor_traces_created_at"), table_name="monitor_traces")
    op.drop_table("monitor_traces")
    op.drop_table("monitor_tenants")
    op.drop_index(op.f("ix_monitor_alerts_tenant"), table_name="monitor_alerts")
    op.drop_index(op.f("ix_monitor_alerts_scope"), table_name="monitor_alerts")
    op.drop_table("monitor_alerts")
    op.drop_index(op.f("ix_experiments_name"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_table("evaluation_suites")
    op.drop_table("diagnosis_benchmarks")
    op.drop_table("chaos_campaigns")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
